services:
  web:
    image: nicopaez/jobvacancy-ruby:1.3.0
    links:
      - db
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
      RACK_ENV: "production"
      DATABASE_URL: "postgres://postgres:Passw0rd!@db:5432/postgres"
    networks:
      - db-web
      - web-network
    depends_on:
      - db
    secrets:
      - db-password
  db:
    image: postgres:14.4-alpine
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    secrets:
      - db-password
    networks:
      - db-web
secrets:
  db-password:
    file: ./secret.txt
networks:
  db-web: {}
  web-network: {}